# Load http_archive from http.bzl
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
# Download apple rules, always check and download the latest version. Here is 1.0.1
http_archive(
    name = "build_bazel_rules_apple",
    sha256 = "36072d4f3614d309d6a703da0dfe48684ec4c65a89611aeb9590b45af7a3e592",
    url = "https://github.com/bazelbuild/rules_apple/releases/download/1.0.1/rules_apple.1.0.1.tar.gz",
)
# Load apple rule 
load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)
# Apple rule required to call this function
apple_rules_dependencies()